In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.3.0'

In [4]:
hello = tf.constant("Hello")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [7]:
print(hello)

tf.Tensor(b'Hello', shape=(), dtype=string)


In [18]:
with tf.Session() as sess:
  sess.run(hello+world)

AttributeError: ignored

In [20]:
# To avoid error 
# In new version of tensorflow

tf.print(hello+world)

HelloWorld


In [19]:
a =tf.constant([2])
b= tf.constant([3])

In [12]:
a

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

In [13]:
c = tf.add(a,b)

In [15]:
# with tf.Session() as session:
#   session.run(c)

# Solution
tf.print(c)

[5]


In [16]:
tf.print(a)

[2]


In [17]:
tf.print(b)

[3]


In [22]:
mat = tf.constant([[1,2,3],[2,3,4]])

In [23]:
tf.print(mat)

[[1 2 3]
 [2 3 4]]


In [28]:
mat1 = tf.constant([[1, 2, 3],[2, 3, 4],[2, 5, 6],[4, 5, 6]])

In [29]:
tf.print(mat1)

[[1 2 3]
 [2 3 4]
 [2 5 6]
 [4 5 6]]


In [31]:
one = tf.constant(1)
two = tf.constant(4)
tf.assign(one,two)
tf.print(new_one)
tf.print(tf.add(one,two))

AttributeError: ignored

In [ ]:
|